### ISSUE TITLE
[Bug] can't run docui on linux

### ISSUE THREAD

**Issue by skanehira** [skanehira/docui#49]
when run docui on linux, there have an error.

error:
```
panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
github.com/skanehira/docui/common.NewLogger(0xc00019a030)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/common/logger.go:20 +0x1c7
github.com/skanehira/docui/panel.New(0x2, 0x83dee0)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/gui.go:91 +0x81
main.main()
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/main.go:13 +0x2e
```

cause:
https://github.com/golang/go/issues/6376

**Comment by skanehira** [comment]
Fixed https://github.com/skanehira/docui/commit/bcec483098729876373000e9e6a406de603f76a0
