### ISSUE TITLE
[Improvement] If can't connect docker engine, it will panic

### ISSUE THREAD

**Issue by skanehira** [skanehira/docui#75]
When run docui and if can't connect docker engine, it will pacni.

````
panic: unable to connect to Docker

goroutine 1 [running]:
github.com/skanehira/docui/panel.(*Gui).init(0xc000082180)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/gui.go:196 +0xf57
github.com/skanehira/docui/panel.New(0x2, 0xc00000e0a8, 0x0)
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/panel/gui.go:92 +0x12a
main.main()
        /Users/skanehira/dev/go/src/github.com/skanehira/docui/main.go:24 +0x208
exit status 2
```

**Comment by skanehira** [comment]
This was completed
